export const FlottoQuestType = {
  ArenaCoins: 1,
  Custom: 2,
  CustomHD: 3,
  EffBeg: 4,
  EffInt: 5,
  EffExp: 6,
  Gems: 7,
  Experience: 8,
  MineCoin: 9,
  NfBeg: 10,
  NfInt: 11,
  NfExp: 12,
  NfHard: 13,
  NfEvil: 14,
  PvP: 15,
  WinStreakBeg: 16,
  WinStreakInt: 17,
  WinStreakExp: 18,
  WinsBeg: 19,
  WinsInt: 20,
  WinsExp: 21,
  WinsMed: 22,
  WinsHard: 23,
  WinsEvil: 24,
  ArenaSpeed: 25,
  ArenaSpeedNG: 26,
  ArenaNoFlags: 27,
  ArenaEfficiency: 28,
  ArenaHighDifficulty: 29,
  ArenaRandomDifficulty: 30,
  ArenaHardcore: 31,
  ArenaHardcoreNG: 32,
  GemRuby: 33,
  GemSapphire: 34,
  GemTopaz: 35,
  GemOnyx: 36,
  GemAquamarine: 37,
  GemEmerald: 38,
  GemJade: 39,
} as const;

export type FlottoQuestId = (typeof FlottoQuestType)[keyof typeof FlottoQuestType];
