const questDescriptions = {
  level_1: "Beginner",
  level_2: "Intermediate",
  level_3: "Expert",
  level_4: "Custom",
  level_11: "Easy",
  level_12: "Medium",
  level_13: "Hard",
  level_14: "Evil",
  level_15: "Custom",
  level_50: "PvP",
  level_51: "PvP",
  level_1_article: "a",
  level_2_article: "an",
  level_3_article: "an",
  level_4_article: "a",
  level_11_article: "an",
  level_12_article: "a",
  level_13_article: "a",
  level_14_article: "an",
  level_15_article: "a",
  level_50_article: "a",
  level_51_article: "a",

  quests_1: "Win %level% level game within %duration% sec",
  quests_9_single: "Earn 1 honour point",
  quests_9_multiple: "Earn %amount% honour points",
  quests_10: "Earn %amount% experience points",
  quests_20: "Earn %amount% experience points in games",
  quests_11: "Earn %amount% minecoins",
  quests_21: "Earn %amount% minecoins in games",
  quests_30: "Earn %amount% event points",
  quests_12: "Win a custom game with a size of %size%",
  quests_13: "Win %amount% out of 100 %level% level games",
  quests_14: "Win %amount% %level% level games in a row",
  quests_eff_single: "Win %level% level game with an efficiency of %eff% or above",
  quests_eff_multiple: "Win %amount% %level% level games with an efficiency of %eff% or above",
  quests_wins_single: "Win %level% level game",
  quests_wins_multiple: "Win %amount% %level% level games",
  quests_19_single: "Win %level% level game without hints",
  quests_19_multiple: "Win %amount% %level% level games without hints",
  quests_17_single: "Win %level% level game with no flags",
  quests_17_multiple: "Win %amount% %level% level games with no flags",
  quests_40_single: "Complete a game in %pvp% mode.",
  quests_40_multiple: "Complete %amount% games in %pvp% mode",
  quests_18_single: "Complete the arena at any level",
  quests_18_multiple: "Earn %amount% arena coins",
  quests_25_single: "Complete the arena at any level",
  quests_25_multiple: "Complete the arena at level %amount% or higher",
  quests_26: "Complete %type% arena or higher",
  quests_101: "Win %amount% %level% level games within 24 hours",
  quests_102_single: "Find an arena ticket",
  quests_102_multiple: "Find %amount% arena tickets",
  quests_103_single: "Find a gem",
  quests_103_multiple: "Find %amount% gems",
  quests_23_single: "Find a gem in games",
  quests_23_multiple: "Find %amount% gems in games",
  quests_104: "Find %amount% %gems%",
  quests_127: "Daily login reward",

  arena_type_1: "Speed",
  arena_type_2: "Speed NG",
  arena_type_3: "No flags",
  arena_type_4: "Efficiency",
  arena_type_5: "High difficulty",
  arena_type_6: "Random difficulty",
  arena_type_7: "Hardcore",
  arena_type_8: "Hardcore NG",
  arena_type_9: "Endurance",
  arena_type_10: "Nightmare",
  arena_type_11: "Ice arena",
  arena_type_13: "Flower arena",
  arena_type_15: "Fruit arena",
  arena_type_16: "Championship",
  arena_type_17: "Championship",
  arena_type_18: "Royale",

  gem_1: "Topaz",
  gem_2: "Ruby",
  gem_3: "Sapphire",
  gem_4: "Amethyst",
  gem_5: "Onyx",
  gem_6: "Aquamarine",
  gem_7: "Emerald",
  gem_8: "Garnet",
  gem_9: "Jade",
  gem_10: "Diamond",
  gems_1: "topazes",
  gems_2: "rubies",
  gems_3: "sapphires",
  gems_4: "amethysts",
  gems_5: "onyxes",
  gems_6: "aquamarines",
  gems_7: "emeralds",
  gems_8: "garnets",
  gems_9: "jades",
  gems_10: "diamonds",
} as Record<string, string>;

export const applyDescription = (key: string, r?: Record<string, string | number>) => {
  let desc = questDescriptions[key] as string;

  if (r) {
    Object.entries(r).forEach(([variable, value]) => {
      desc = desc.replaceAll(variable, `${value}`);
    });
  }

  return desc;
};
